development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sinatrails_development
  pool: 5
  username: root
  password:

  # slackware socket
  socket: /var/run/mysql/mysql.sock

  # ubuntu socket
  #socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sinatrails_test
  pool: 5
  username: root
  password:
  # slackware socket
  socket: /var/run/mysql/mysql.sock

  # ubuntu socket
  #socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sinatrails_production
  pool: 5
  username: root
  password:
  # slackware socket
  socket: /var/run/mysql/mysql.sock

  # ubuntu socket
  #socket: /var/run/mysqld/mysqld.sock
