#!/usr/bin/env ruby

require File.join(File.expand_path('../../config/', __FILE__), 'boot.rb')
require File.join(File.expand_path('../../config/', __FILE__), 'application.rb')

require "irb"
require "irb/completion"

# NOTE: Taken from irb script
#   	by Keiju ISHITSUKA(keiju@ruby-lang.org)
#

if __FILE__ == $0
  IRB.start(__FILE__)
else
  # check -e option
  if /^-e$/ =~ $0
    IRB.start(__FILE__)
  else
    IRB.setup(__FILE__)
  end
end
