#!/usr/bin/env ruby

require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: ./scripts/test [options] [arguments]"

  opts.on("-u", "--unit [FILENAME]", "Run unit test") do |unit|
    dir = File.expand_path("../../test/unit/", __FILE__)
    unit = Dir[File.join(dir, '*.rb')].map{|file| File.basename(file)}.join(",").gsub("_test.rb", "") if unit.nil?
    options[:unit] = unit
  end

  opts.on("-i", "--integration [FILENAME]", "Run integration test") do |integration|
    dir = File.expand_path("../../test/integration/", __FILE__)
    integration = Dir[File.join(dir, '*.rb')].map{|file| File.basename(file)}.join(",").gsub("_test.rb", "") if integration.nil?
    options[:integration] = integration
  end
end.parse!

options.each do |key, value|
  puts "Run #{key} test: #{value}"
  dir = File.expand_path("../../test/#{key}/", __FILE__)
  if !value.nil?
    value.split(",").each do |file|
      load dir + "/#{file}_test.rb"
    end
  else
    Dir[FIle.join(dir, '*.rb')].each do |file|
      load file
    end
  end
end
